#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".[tj]sx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# Check for eslint
ESLINT="./node_modules/.bin/eslint"
if [[ ! -e $ESLINT ]]; then
  echo
  echo -e "  \033[41mPlease use <yarn> to install ESlint\033[0m"
  exit 1
fi;

TSLINT="./node_modules/.bin/tslint"
if [[ ! -e $TSLINT ]]; then
  echo
  echo -e "  \033[41mPlease use <yarn> to install TSLINT\033[0m"
  exit 1
fi;

PASS=true

for FILE in $STAGED_FILES
do
  if [[ `echo "$FILE" | grep '\.jsx\{0,1\}$'` ]]; then
    $ESLINT "$FILE"
    if [[ "$?" == 0 ]]; then
      echo -e "  \033[32mESLint Passed: $FILE\033[0m"
    else
      echo -e "  \033[41mESLint Failed: $FILE\033[0m"
      PASS=false
    fi
  elif [[ `echo "$FILE" | grep '\.tsx\{0,1\}$'` ]]; then
    $TSLINT --format verbose "$FILE"
    if [[ "$?" == 0 ]]; then
      echo -e "  \033[32mTSLint Passed: $FILE\033[0m"
    else
      echo -e "  \033[41mTSLint Failed: $FILE\033[0m"
      PASS=false
    fi;
  fi;
done

if ! $PASS; then
  echo -e "\n\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint/TSLint but do not. Please fix the ESLint/TSLint errors and try again.\n"
  exit 1
fi

exit $?
